# Change these first
owner: hoangthuan24062002 # Your GitHub organization or username, where this repository lives
repo: upp # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: QBU
    url: https://qbu.edu.vn
  - name: Quan ly dao tao
    url: http://daotao.quangbinhuni.edu.vn
  - name: Tai nguyen mo
    url: http://lrc.quangbinhuni.edu.vn:8383/dspace
  - name: Tap chi khoa hoc
    url: http://tckh.qbu.edu.vn/index.php/tckh
  - name: UBND tinh Quang Binh
    url: https://quangbinh.gov.vn
  - name: Bo GDDT
    url: https://moet.gov.vn/Pages/home.aspx
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upp
  logoUrl: https://avatars.githubusercontent.com/u/74901479?s=400&u=a355712eaef206ddc75aef8952596afd0270f726&v=4
  name: Upptime
  introTitle: "Đây là hệ thống giám sát hoạt động trang web của hoangthuan24062002."
  introMessage: Trang web sử dụng liệu thời gian thực từ [GitHub repository](https://github.com/hoangthuan24062002/upp). Không sử dụng máy chủ — Chỉ sử dụng GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/hoangthuan24062002/upp

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
